spring:
  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USER}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect

server:
  error:
    include-stacktrace: never

API:
  security:
    token:
      secret: ajudardev