spring:
  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USER}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: "/"

server:
  error:
    include-stacktrace: never
  max-http-header-size: 50MB

API:
  security:
    token:
      secret: 26dc88296acca1fcf780fb1e5928478a4538b766dedc247228568505f8773fd9
      expiration: 8640000